version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default
    volumes:
      - ./database/sql/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
  
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "source-topic:1:1,success-topic"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock